spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rockalendar
    username: rockalendar
    password: rockalendar
    driver-class-name: org.postgresql.Driver

# =================================
# MAILHOG
# Intercepta los emails para que no lleguen a bandejas de correo reales
# =================================
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# =================================
# PROPERTIES
# =================================
rockalendar:
  frontend:
    base-url: "http://localhost:3000"
  storage:
    endpoint: "http://localhost:9000"
    bucket: "rockalendar"
    access-key: "rockalendar"
    secret-key: "rockalendar"
    public-url-base: "http://localhost:9000/rockalendar"
