spring:
  application:
    name: rockalendar

  jpa:
    hibernate:
      ddl-auto: validate # Flyway manda
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# propiedades de la app
rockalendar:
  search:
    public:
      minSimilarity: 0.30
      ftsWeight: 2.0
      trgmWeight: 1.0